### ISSUE TITLE
Workaround/Update for setting up Conda env on the container

### ISSUE THREAD

**Issue by jk-tripathy** [DFKI-NLP/pegasus-bridle#8]
The current `.env` file requires conda to be installed in the container before a custom env can be used. This can be bypassed by mounting the entire `conda` dir found at the netscratch head node to the container rather than just the env folder.

Suggested fix to `.env.example` file:
```
# change this if you have installed miniconda to another location
HOST_CONDA_ENVS_DIR=/netscratch/$USER/miniconda3/
# change this if you use another Enroot image with a different conda location
CONTAINER_CONDA_ENVS_DIR=/opt/conda/
```

By mounting the entire `conda` folder the initial `source /opt/conda/bin/activate` in `activate_and_execute.sh` can never fail allowing the custom env activated when wanted.

**Comment by ArneBinder** [comment]
cc @leonhardhennig
